[package]
name = "is-prime"
authors = ["Baris Bayrak <baris@bayrak.dev>"]
version = "0.1.0"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
primal = "0.3"